---
  - name: install php packages
    yum:
      pkg={{ item }}
      state=present
    with_items:
      - php70
      - php70-gd
      - php70-json
      - php70-mbstring
      - php70-mcrypt
      - php70-mysqlnd
      - php70-pdo
      - php70-xml
      - php70-zip
  - name: install composer
    shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin && mv /usr/local/bin/composer.phar /usr/local/bin/composer
           creates=/usr/local/bin/composer
